
services:
  control-plane:
    image: hyperflex/hyperflexcontrolplane:latest
    container_name: control-plane
    environment:
      - MODULES=capacity_planner  # Define modules here
      - CAPACITY_PLANNER_URL=http://capacity-planner:3000/api/v1/capacity-planning
    ports:
      - "8000:8000"
    depends_on:
      - capacity-planner


  capacity-planner:

    image: hyperflex/s2e-capacity-planner-service
    container_name: capacity-planner
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=1
    ports:
      - "3000:3000"