
services:
  control-plane:
    image: ayushhyperflex/hyperflexcontrolplane:latest
    container_name: control-plane
    environment:
      - MODULES=capacity_planner  # Define modules here
      - CAPACITY_PLANNER_URL=http://capacity-planner:3000/api/v1/capacity-planning
    ports:
      - "8000:8000"
    depends_on:
      - capacity-planner


  capacity-planner:

    image: capacity_planner
    container_name: capacity-planner
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=1
    ports:
      - "3000:3000"