version: "3.10"

services:
  core:
    container_name: splunk-migrator-core
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
#    depends_on:
#      - redis
#    environment:
#      - REDIS_URL=redis://redis:6379/0

#  redis:
#    image: redis:7
#    container_name: splunk-migrator-redis
#    ports:
#      - "6379:6379"
#    restart: always
